project_id = "bnuadaqkcwefdknpdqyl"

[functions.submit-application]
verify_jwt = false

[functions.admin-login]
verify_jwt = false

[functions.admin-list-applications]
verify_jwt = false

[functions.admin-update-application]
verify_jwt = false

[functions.admin-export-csv]
verify_jwt = false

[functions.admin-delete-application]
verify_jwt = false